"""
train_rcnn.py
-------------
Training pipeline for the Faster R-CNN defect detection model.
Optimized for CPU training with:
  - Frozen backbone (only trains detection head)
  - Subset sampling for faster epochs
  - Smaller image preprocessing
Auto-generates bounding-box annotations from existing data using
contour detection on preprocessed defect masks.
"""

import os
import cv2
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader, Subset
import torchvision.transforms.functional as F
from PIL import Image
import random
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from preprocess import load_image, focus_on_object, resize, full_pipeline
from rcnn_model import build_rcnn_model, get_device, NUM_CLASSES


MODELS_DIR = os.path.join(os.path.dirname(__file__), "..", "models")
RESULTS_DIR = os.path.join(os.path.dirname(__file__), "..", "results")

IMG_SIZE = 224
MAX_TRAIN_SAMPLES = 200  # Cap for fast CPU training


class DefectDataset(Dataset):
    """
    PyTorch Dataset for defect detection with Faster R-CNN.

    For *defective* images, bounding boxes are auto-generated by running
    contour detection on the preprocessed binary mask.
    For *good* images, targets contain no boxes (background only).
    """

    def __init__(self, data_dir: str):
        self.samples = []  # list of (image_path, label_id)

        for label_name, label_id in [("good", 0), ("defective", 1)]:
            folder = os.path.join(data_dir, label_name)
            if not os.path.exists(folder):
                continue
            for fname in os.listdir(folder):
                if fname.lower().endswith((".png", ".jpg", ".jpeg", ".bmp")):
                    self.samples.append((os.path.join(folder, fname), label_id))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label_id = self.samples[idx]

        # Load and preprocess
        img_bgr = load_image(img_path)
        focused = focus_on_object(img_bgr)
        resized = resize(focused, (IMG_SIZE, IMG_SIZE))

        # Convert BGR -> RGB -> tensor (float [0,1])
        img_rgb = cv2.cvtColor(resized, cv2.COLOR_BGR2RGB)
        img_tensor = F.to_tensor(img_rgb)  # [3, H, W] float32

        # Build target
        boxes = []
        labels = []

        if label_id == 1:
            # Auto-generate bbox annotations from contour detection
            cleaned = full_pipeline(focused)
            contours, _ = cv2.findContours(
                cleaned, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE
            )
            contours = [c for c in contours if cv2.contourArea(c) > 30]

            # Scale contour coords to the resized image dimensions
            orig_h, orig_w = cleaned.shape[:2]
            scale_x = IMG_SIZE / orig_w
            scale_y = IMG_SIZE / orig_h

            for cnt in contours[:15]:  # limit to top 15 detections
                x, y, w, h = cv2.boundingRect(cnt)
                x1 = max(0, int(x * scale_x))
                y1 = max(0, int(y * scale_y))
                x2 = min(IMG_SIZE, int((x + w) * scale_x))
                y2 = min(IMG_SIZE, int((y + h) * scale_y))

                if (x2 - x1) > 2 and (y2 - y1) > 2:
                    boxes.append([x1, y1, x2, y2])
                    labels.append(1)  # defect class

        # If defective but no contours found, add a small center fallback box
        if label_id == 1 and len(boxes) == 0:
            cx, cy = IMG_SIZE // 2, IMG_SIZE // 2
            boxes.append([cx - 20, cy - 20, cx + 20, cy + 20])
            labels.append(1)

        if len(boxes) > 0:
            boxes_tensor = torch.as_tensor(boxes, dtype=torch.float32)
            labels_tensor = torch.as_tensor(labels, dtype=torch.int64)
        else:
            boxes_tensor = torch.zeros((0, 4), dtype=torch.float32)
            labels_tensor = torch.zeros((0,), dtype=torch.int64)

        target = {
            "boxes": boxes_tensor,
            "labels": labels_tensor,
            "image_id": idx,
        }

        return img_tensor, target


def collate_fn(batch):
    """Custom collate to handle variable-size targets."""
    return tuple(zip(*batch))


def train_rcnn_model(data_dir: str, epochs: int = 10, lr: float = 0.005,
                     progress_callback=None) -> dict:
    """
    Train the Faster R-CNN model on the defect dataset.
    Optimized for CPU: frozen backbone, sample cap, efficient batching.

    Args:
        data_dir: Path to training data (contains good/ and defective/ subfolders)
        epochs: Number of training epochs
        lr: Learning rate
        progress_callback: Optional callable(progress_float, message_str)

    Returns:
        Dict with training results and paths to saved artifacts.
    """
    os.makedirs(MODELS_DIR, exist_ok=True)
    os.makedirs(RESULTS_DIR, exist_ok=True)
    device = get_device()

    if progress_callback:
        progress_callback(0.05, "Loading dataset...")

    full_dataset = DefectDataset(data_dir)
    if len(full_dataset) == 0:
        raise ValueError("No images found. Check data directory structure.")

    # Subsample for faster CPU training
    n_total = len(full_dataset)
    if n_total > MAX_TRAIN_SAMPLES:
        indices = random.sample(range(n_total), MAX_TRAIN_SAMPLES)
        dataset = Subset(full_dataset, indices)
        n_used = MAX_TRAIN_SAMPLES
    else:
        dataset = full_dataset
        n_used = n_total

    dataloader = DataLoader(
        dataset, batch_size=2, shuffle=True,
        collate_fn=collate_fn, num_workers=0
    )

    if progress_callback:
        progress_callback(0.10, f"Using {n_used}/{n_total} images. Building R-CNN model...")

    model = build_rcnn_model(pretrained_backbone=True, freeze_backbone=True)
    model.to(device)
    model.train()

    # Only train non-frozen params (detection head)
    params = [p for p in model.parameters() if p.requires_grad]
    optimizer = torch.optim.SGD(params, lr=lr, momentum=0.9, weight_decay=0.0005)
    lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=max(1, epochs // 3), gamma=0.5)

    # Count classes from full dataset
    n_good = sum(1 for _, lid in full_dataset.samples if lid == 0)
    n_defective = sum(1 for _, lid in full_dataset.samples if lid == 1)

    epoch_losses = []

    if progress_callback:
        progress_callback(0.15, f"Training R-CNN for {epochs} epochs on {device} (head only, backbone frozen)...")

    for epoch in range(epochs):
        running_loss = 0.0
        batch_count = 0

        for images, targets in dataloader:
            images = [img.to(device) for img in images]
            targets = [{k: v.to(device) for k, v in t.items()
                       if isinstance(v, torch.Tensor)} for t in targets]

            # Filter out samples with no boxes (good images)
            # Faster R-CNN requires at least one box per target
            valid_pairs = [(img, tgt) for img, tgt in zip(images, targets)
                          if tgt["boxes"].shape[0] > 0]

            if len(valid_pairs) == 0:
                continue

            valid_images, valid_targets = zip(*valid_pairs)

            loss_dict = model(list(valid_images), list(valid_targets))
            losses = sum(loss for loss in loss_dict.values())

            optimizer.zero_grad()
            losses.backward()
            torch.nn.utils.clip_grad_norm_(params, max_norm=5.0)
            optimizer.step()

            running_loss += losses.item()
            batch_count += 1

        lr_scheduler.step()

        avg_loss = running_loss / max(batch_count, 1)
        epoch_losses.append(avg_loss)

        if progress_callback:
            pct = 0.15 + (epoch + 1) / epochs * 0.65
            progress_callback(min(pct, 0.80),
                            f"Epoch {epoch+1}/{epochs} — Loss: {avg_loss:.4f}")

    if progress_callback:
        progress_callback(0.82, "Evaluating on test set...")

    # --- Evaluate on test data ---
    test_dir = os.path.join(os.path.dirname(data_dir), "test")
    test_results = _evaluate_rcnn(model, test_dir, device) if os.path.exists(test_dir) else None

    if progress_callback:
        progress_callback(0.90, "Saving model and plots...")

    # --- Save model ---
    model_path = os.path.join(MODELS_DIR, "rcnn_model.pth")
    torch.save({
        "model_state_dict": model.state_dict(),
        "num_classes": NUM_CLASSES,
        "epochs_trained": epochs,
        "final_loss": epoch_losses[-1] if epoch_losses else 0,
    }, model_path)

    # --- Plot loss curve ---
    loss_plot_path = _plot_loss_curve(epoch_losses, RESULTS_DIR)

    if progress_callback:
        progress_callback(1.0, "R-CNN training complete!")

    results = {
        "n_samples": n_used,
        "n_good": n_good,
        "n_defective": n_defective,
        "epochs": epochs,
        "epoch_losses": epoch_losses,
        "final_loss": epoch_losses[-1] if epoch_losses else 0,
        "loss_plot_path": loss_plot_path,
        "model_path": model_path,
        "device": str(device),
        "test_results": test_results,
    }

    # Add accuracy + f1 from test_results if available
    if test_results:
        results["accuracy"] = test_results["accuracy"]
        results["f1_score"] = test_results["f1_score"]
    else:
        results["accuracy"] = 0.0
        results["f1_score"] = 0.0

    return results


def _evaluate_rcnn(model, test_dir: str, device) -> dict:
    """Evaluate R-CNN on test set (image-level classification accuracy)."""
    model.eval()
    full_dataset = DefectDataset(test_dir)
    if len(full_dataset) == 0:
        return None

    # Cap evaluation too for speed
    n_eval = min(len(full_dataset), 80)
    if n_eval < len(full_dataset):
        indices = random.sample(range(len(full_dataset)), n_eval)
        dataset = Subset(full_dataset, indices)
    else:
        dataset = full_dataset

    correct = 0
    total = 0
    y_true = []
    y_pred = []

    with torch.no_grad():
        for i in range(len(dataset)):
            img_tensor, target = dataset[i]
            img_tensor = img_tensor.to(device)
            predictions = model([img_tensor])
            pred = predictions[0]

            # Image-level: if any detection has score > 0.5 → defective
            true_label = 1 if target["labels"].numel() > 0 and target["labels"].max().item() > 0 else 0
            has_defect = False
            if len(pred["scores"]) > 0:
                high_conf = pred["scores"] > 0.5
                if high_conf.any():
                    has_defect = True

            pred_label = 1 if has_defect else 0
            y_true.append(true_label)
            y_pred.append(pred_label)

            if pred_label == true_label:
                correct += 1
            total += 1

    model.train()

    from sklearn.metrics import classification_report, f1_score, confusion_matrix

    accuracy = correct / max(total, 1)
    f1 = f1_score(y_true, y_pred, average="weighted", zero_division=0)
    report = classification_report(y_true, y_pred, target_names=["Good", "Defective"],
                                   zero_division=0)
    cm = confusion_matrix(y_true, y_pred)

    # Save test confusion matrix
    cm_path = _plot_rcnn_confusion_matrix(cm, RESULTS_DIR)

    return {
        "n_samples": total,
        "accuracy": accuracy,
        "f1_score": f1,
        "report": report,
        "confusion_matrix": cm,
        "cm_path": cm_path,
    }


def _plot_loss_curve(losses: list, save_dir: str) -> str:
    """Plot training loss curve."""
    fig, ax = plt.subplots(figsize=(7, 4))
    fig.patch.set_facecolor("#0f1117")
    ax.set_facecolor("#0f1117")

    ax.plot(range(1, len(losses) + 1), losses, color="#3b82f6", linewidth=2,
            marker="o", markersize=5, markerfacecolor="#60a5fa")
    ax.fill_between(range(1, len(losses) + 1), losses,
                    alpha=0.1, color="#3b82f6")
    ax.set_xlabel("Epoch", color="white", fontsize=12)
    ax.set_ylabel("Loss", color="white", fontsize=12)
    ax.set_title("R-CNN Training Loss", color="white", fontsize=14, pad=15)
    ax.tick_params(colors="white")
    for spine in ax.spines.values():
        spine.set_edgecolor("#333")
    ax.grid(True, alpha=0.15, color="white")

    plt.tight_layout()
    path = os.path.join(save_dir, "rcnn_loss_curve.png")
    plt.savefig(path, dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close()
    return path


def _plot_rcnn_confusion_matrix(cm, save_dir: str) -> str:
    """Plot confusion matrix for R-CNN evaluation."""
    import seaborn as sns

    fig, ax = plt.subplots(figsize=(6, 5))
    fig.patch.set_facecolor("#0f1117")
    ax.set_facecolor("#0f1117")

    sns.heatmap(
        cm, annot=True, fmt="d", cmap="Blues",
        xticklabels=["Good", "Defective"],
        yticklabels=["Good", "Defective"],
        ax=ax, linewidths=0.5,
        annot_kws={"size": 16, "color": "white"},
    )
    ax.set_xlabel("Predicted", color="white", fontsize=12)
    ax.set_ylabel("Actual", color="white", fontsize=12)
    ax.set_title("R-CNN Test Confusion Matrix", color="white", fontsize=14, pad=15)
    ax.tick_params(colors="white")
    for spine in ax.spines.values():
        spine.set_edgecolor("#333")

    plt.tight_layout()
    path = os.path.join(save_dir, "rcnn_confusion_matrix.png")
    plt.savefig(path, dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close()
    return path


def load_rcnn_model():
    """Load a trained R-CNN model from disk."""
    model_path = os.path.join(MODELS_DIR, "rcnn_model.pth")
    if not os.path.exists(model_path):
        return None

    device = get_device()
    model = build_rcnn_model(pretrained_backbone=False, freeze_backbone=False)

    checkpoint = torch.load(model_path, map_location=device, weights_only=False)
    model.load_state_dict(checkpoint["model_state_dict"])
    model.to(device)
    model.eval()
    return model


if __name__ == "__main__":
    import sys
    data_dir = sys.argv[1] if len(sys.argv) > 1 else "data/train"

    def progress(val, msg):
        print(f"  [{val*100:5.1f}%] {msg}")

    results = train_rcnn_model(data_dir, epochs=5, progress_callback=progress)
    print(f"\nR-CNN training complete. Final loss: {results['final_loss']:.4f}")
    if results.get("test_results"):
        print(f"Test accuracy: {results['test_results']['accuracy']:.3f}")
